alter type "public"."invite_status" rename to "invite_status__old_version_to_be_dropped";

create type "public"."invite_status" as enum ('pending', 'rejected', 'accepted');

create table "public"."invite_members" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "invited_by_email" text not null,
    "email" text not null,
    "status" invite_status not null default 'pending'::invite_status,
    "house_id" bigint not null,
    "house_name" text not null
);


alter table "public"."invite_members" enable row level security;

drop type "public"."invite_status__old_version_to_be_dropped";

CREATE UNIQUE INDEX invite_members_pkey ON public.invite_members USING btree (id);

alter table "public"."invite_members" add constraint "invite_members_pkey" PRIMARY KEY using index "invite_members_pkey";

grant delete on table "public"."invite_members" to "anon";

grant insert on table "public"."invite_members" to "anon";

grant references on table "public"."invite_members" to "anon";

grant select on table "public"."invite_members" to "anon";

grant trigger on table "public"."invite_members" to "anon";

grant truncate on table "public"."invite_members" to "anon";

grant update on table "public"."invite_members" to "anon";

grant delete on table "public"."invite_members" to "authenticated";

grant insert on table "public"."invite_members" to "authenticated";

grant references on table "public"."invite_members" to "authenticated";

grant select on table "public"."invite_members" to "authenticated";

grant trigger on table "public"."invite_members" to "authenticated";

grant truncate on table "public"."invite_members" to "authenticated";

grant update on table "public"."invite_members" to "authenticated";

grant delete on table "public"."invite_members" to "service_role";

grant insert on table "public"."invite_members" to "service_role";

grant references on table "public"."invite_members" to "service_role";

grant select on table "public"."invite_members" to "service_role";

grant trigger on table "public"."invite_members" to "service_role";

grant truncate on table "public"."invite_members" to "service_role";

grant update on table "public"."invite_members" to "service_role";


