create table "public"."kitchen_recipe_ingredients" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "house_id" bigint not null,
    "recipe_id" uuid not null default gen_random_uuid(),
    "ingredient" text not null,
    "step_number" bigint not null
);


alter table "public"."kitchen_recipe_ingredients" enable row level security;

create table "public"."kitchen_recipe_instructions" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "recipe_id" uuid not null default gen_random_uuid(),
    "house_id" bigint not null,
    "instruction" text not null,
    "step_number" bigint not null
);


alter table "public"."kitchen_recipe_instructions" enable row level security;

create table "public"."kitchen_recipes" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "image_url" text,
    "title" text not null,
    "description" text,
    "source_url" text,
    "house_id" bigint not null
);


alter table "public"."kitchen_recipes" enable row level security;

CREATE UNIQUE INDEX kitchen_recipe_ingredients_pkey ON public.kitchen_recipe_ingredients USING btree (id);

CREATE UNIQUE INDEX kitchen_recipe_instructions_pkey ON public.kitchen_recipe_instructions USING btree (id);

CREATE UNIQUE INDEX kitchen_recipes_pkey ON public.kitchen_recipes USING btree (id);

alter table "public"."kitchen_recipe_ingredients" add constraint "kitchen_recipe_ingredients_pkey" PRIMARY KEY using index "kitchen_recipe_ingredients_pkey";

alter table "public"."kitchen_recipe_instructions" add constraint "kitchen_recipe_instructions_pkey" PRIMARY KEY using index "kitchen_recipe_instructions_pkey";

alter table "public"."kitchen_recipes" add constraint "kitchen_recipes_pkey" PRIMARY KEY using index "kitchen_recipes_pkey";

alter table "public"."kitchen_recipe_ingredients" add constraint "kitchen_recipe_ingredients_recipe_id_fkey" FOREIGN KEY (recipe_id) REFERENCES kitchen_recipes(id) not valid;

alter table "public"."kitchen_recipe_ingredients" validate constraint "kitchen_recipe_ingredients_recipe_id_fkey";

alter table "public"."kitchen_recipe_instructions" add constraint "kitchen_recipe_instructions_recipe_id_fkey" FOREIGN KEY (recipe_id) REFERENCES kitchen_recipes(id) not valid;

alter table "public"."kitchen_recipe_instructions" validate constraint "kitchen_recipe_instructions_recipe_id_fkey";

grant delete on table "public"."kitchen_recipe_ingredients" to "anon";

grant insert on table "public"."kitchen_recipe_ingredients" to "anon";

grant references on table "public"."kitchen_recipe_ingredients" to "anon";

grant select on table "public"."kitchen_recipe_ingredients" to "anon";

grant trigger on table "public"."kitchen_recipe_ingredients" to "anon";

grant truncate on table "public"."kitchen_recipe_ingredients" to "anon";

grant update on table "public"."kitchen_recipe_ingredients" to "anon";

grant delete on table "public"."kitchen_recipe_ingredients" to "authenticated";

grant insert on table "public"."kitchen_recipe_ingredients" to "authenticated";

grant references on table "public"."kitchen_recipe_ingredients" to "authenticated";

grant select on table "public"."kitchen_recipe_ingredients" to "authenticated";

grant trigger on table "public"."kitchen_recipe_ingredients" to "authenticated";

grant truncate on table "public"."kitchen_recipe_ingredients" to "authenticated";

grant update on table "public"."kitchen_recipe_ingredients" to "authenticated";

grant delete on table "public"."kitchen_recipe_ingredients" to "service_role";

grant insert on table "public"."kitchen_recipe_ingredients" to "service_role";

grant references on table "public"."kitchen_recipe_ingredients" to "service_role";

grant select on table "public"."kitchen_recipe_ingredients" to "service_role";

grant trigger on table "public"."kitchen_recipe_ingredients" to "service_role";

grant truncate on table "public"."kitchen_recipe_ingredients" to "service_role";

grant update on table "public"."kitchen_recipe_ingredients" to "service_role";

grant delete on table "public"."kitchen_recipe_instructions" to "anon";

grant insert on table "public"."kitchen_recipe_instructions" to "anon";

grant references on table "public"."kitchen_recipe_instructions" to "anon";

grant select on table "public"."kitchen_recipe_instructions" to "anon";

grant trigger on table "public"."kitchen_recipe_instructions" to "anon";

grant truncate on table "public"."kitchen_recipe_instructions" to "anon";

grant update on table "public"."kitchen_recipe_instructions" to "anon";

grant delete on table "public"."kitchen_recipe_instructions" to "authenticated";

grant insert on table "public"."kitchen_recipe_instructions" to "authenticated";

grant references on table "public"."kitchen_recipe_instructions" to "authenticated";

grant select on table "public"."kitchen_recipe_instructions" to "authenticated";

grant trigger on table "public"."kitchen_recipe_instructions" to "authenticated";

grant truncate on table "public"."kitchen_recipe_instructions" to "authenticated";

grant update on table "public"."kitchen_recipe_instructions" to "authenticated";

grant delete on table "public"."kitchen_recipe_instructions" to "service_role";

grant insert on table "public"."kitchen_recipe_instructions" to "service_role";

grant references on table "public"."kitchen_recipe_instructions" to "service_role";

grant select on table "public"."kitchen_recipe_instructions" to "service_role";

grant trigger on table "public"."kitchen_recipe_instructions" to "service_role";

grant truncate on table "public"."kitchen_recipe_instructions" to "service_role";

grant update on table "public"."kitchen_recipe_instructions" to "service_role";

grant delete on table "public"."kitchen_recipes" to "anon";

grant insert on table "public"."kitchen_recipes" to "anon";

grant references on table "public"."kitchen_recipes" to "anon";

grant select on table "public"."kitchen_recipes" to "anon";

grant trigger on table "public"."kitchen_recipes" to "anon";

grant truncate on table "public"."kitchen_recipes" to "anon";

grant update on table "public"."kitchen_recipes" to "anon";

grant delete on table "public"."kitchen_recipes" to "authenticated";

grant insert on table "public"."kitchen_recipes" to "authenticated";

grant references on table "public"."kitchen_recipes" to "authenticated";

grant select on table "public"."kitchen_recipes" to "authenticated";

grant trigger on table "public"."kitchen_recipes" to "authenticated";

grant truncate on table "public"."kitchen_recipes" to "authenticated";

grant update on table "public"."kitchen_recipes" to "authenticated";

grant delete on table "public"."kitchen_recipes" to "service_role";

grant insert on table "public"."kitchen_recipes" to "service_role";

grant references on table "public"."kitchen_recipes" to "service_role";

grant select on table "public"."kitchen_recipes" to "service_role";

grant trigger on table "public"."kitchen_recipes" to "service_role";

grant truncate on table "public"."kitchen_recipes" to "service_role";

grant update on table "public"."kitchen_recipes" to "service_role";


