create table "public"."kitchen_grocery_lists" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "house_id" bigint not null,
    "content" text not null
);


alter table "public"."kitchen_grocery_lists" enable row level security;

CREATE UNIQUE INDEX kitchen_grocery_lists_pkey ON public.kitchen_grocery_lists USING btree (id);

alter table "public"."kitchen_grocery_lists" add constraint "kitchen_grocery_lists_pkey" PRIMARY KEY using index "kitchen_grocery_lists_pkey";

grant delete on table "public"."kitchen_grocery_lists" to "anon";

grant insert on table "public"."kitchen_grocery_lists" to "anon";

grant references on table "public"."kitchen_grocery_lists" to "anon";

grant select on table "public"."kitchen_grocery_lists" to "anon";

grant trigger on table "public"."kitchen_grocery_lists" to "anon";

grant truncate on table "public"."kitchen_grocery_lists" to "anon";

grant update on table "public"."kitchen_grocery_lists" to "anon";

grant delete on table "public"."kitchen_grocery_lists" to "authenticated";

grant insert on table "public"."kitchen_grocery_lists" to "authenticated";

grant references on table "public"."kitchen_grocery_lists" to "authenticated";

grant select on table "public"."kitchen_grocery_lists" to "authenticated";

grant trigger on table "public"."kitchen_grocery_lists" to "authenticated";

grant truncate on table "public"."kitchen_grocery_lists" to "authenticated";

grant update on table "public"."kitchen_grocery_lists" to "authenticated";

grant delete on table "public"."kitchen_grocery_lists" to "service_role";

grant insert on table "public"."kitchen_grocery_lists" to "service_role";

grant references on table "public"."kitchen_grocery_lists" to "service_role";

grant select on table "public"."kitchen_grocery_lists" to "service_role";

grant trigger on table "public"."kitchen_grocery_lists" to "service_role";

grant truncate on table "public"."kitchen_grocery_lists" to "service_role";

grant update on table "public"."kitchen_grocery_lists" to "service_role";

create policy "Enable users to create data based on their house ID"
on "public"."kitchen_grocery_lists"
as permissive
for insert
to authenticated
with check (is_user_in_house(house_id));


create policy "Enable users to see their house data"
on "public"."kitchen_grocery_lists"
as permissive
for select
to authenticated
using (is_user_in_house(house_id));


create policy "Enable users to update date that's part of their house"
on "public"."kitchen_grocery_lists"
as permissive
for update
to public
using (is_user_in_house(house_id));



