name: Run Tests

on: push

jobs:
  npm-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22

    - name: Install Node.js dependencies
      run: npm ci

    - run: npm run lint
